### PR TITLE
Addition of Password ability

### PR DESCRIPTION
**Pull request by dsplice**
This pull request includes the ability of using plaintext password to decrypt the document.

### CODE REVIEW

**Comment by nolze** [comment]
Thanks! This is the very essential feature.

I made some additional fixes, testing with some Office 2016 documents at hand. Does it work well for yours, too?

I'm going to add tests and do some refactoring soon.

**Comment by dsplice** [comment]
No worries.  We encountered a LARGE influx of Word Docs with passwords
included in the email.  Got me thinking of how to do more commandline
testing.

As for the fixes, please do!  I am NOT (and extra emphasis NOT) a
programmer, so I am actually surprised I got it to work.

I tested about 100 documents.  Worked for all of them, course they were all
likely created by the same spammer/malicious actor so they might not be
inclusive of all different changes.  I noticed the xml for the encryption
info might change a bit over versions so....

Awesome work btw!  Please keep it up.  I even mentioned it to decalage and
he mentioned he might want to include that ability in the oletools suite.

D

**Comment by nolze** [comment]
Hi @dsplice, I noticed that your name is missing from the [contributors](https://github.com/nolze/msoffcrypto-tool/graphs/contributors) page of this repository.
I guess your email address with which you made the commits is different from the one(s) associated with your GitHub account (I don't put the email address here, but you can check it by cloning this repo  and doing `git log`).

If you don't mind, please [add the email address (in `git log`) to your GitHub account](
https://help.github.com/articles/adding-an-email-address-to-your-github-account/); it would be nice to see you on the contributors page :)

**Comment by dsplice** [comment]
Forgot I used my work email for that one.  Added!  And thanks!

**Pull request merged**
